apiVersion: v1
kind: Service
metadata:
  name: weather-api
  namespace: mrnwaiwu-apps
spec:
  selector:
    app: weather-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
